const eventy=[
{ idx:0, tresc:"Usiadłeś/aś na parapecie gdy obok przechodził nauczyciel i zgarnąłeś/aś uwagę.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:1, tresc:"Powiedziałeś/aś dzień dobry Panu Dyrektorowi. Był zadowolony.</br>Idziesz do przodu o 2 pola.", efekt:(2) },
{ idx:2, tresc:"Okazało się, że dzisiaj jest niezapowiedziana kartkówka ale dostajesz 5.</br>Idziesz do przodu o 3 pola.", efekt:(3) },
{ idx:3, tresc:"Okzało się, żę dzisiaj jest niezapowiedziana kartkówka i dostajesz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:4, tresc:"Okzało się, że dzisiaj jest niezapowiedziana kartkówka z której dostajesz 1 ale przebłagałeś/aś nauczyciela na 2.</br>Nic się nie dzieje.", efekt:(0) },
{ idx:5, tresc:"Razem ze znajomym ścigacie się do portierni ale po drodze widzi was nauczyciel. Dostajecie uwagi.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:6, tresc:"Byłeś chory i przegapiłeś kartkówkę, umawiasz się na nowy termin.</br>Cofasz się o 1 pole.", efekt:(-1) },
{ idx:7, tresc:"Na lekcji puszczasz samoloty z papieru. Nauczyciel nie jest zadowolony.</br>Cofasz się o 2 pola", efekt:(-2) },
{ idx:8, tresc:"Nauczyciel przyłapał cię na używaniu telefonu na lekcji. Dostajesz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:9, tresc:"Czas na sprawdzian. Dostajesz 5.</br>Idziesz o 3 pola do przodu.", efekt:(3) },
{ idx:10, tresc:"Czas na sprawdzian. Niestety dostajesz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:11, tresc:"Nauczyciel postanowił wziąść cię do odpytywania ale akurat masz szczęśliwy numerek.</br>Stoisz tam gdzie stałeś/aś.", efekt:(0) },
{ idx:12, tresc:"Nauczyciel postanowił wziąść cię do odpytwyania niestety nie umiesz. Dostajesz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:13, tresc:"Nauczyciel postanowił wziąść cię do odpytywania na szczęście umiesz. Dostajesz 4.</br>Idziesz do przodu o 2 pola.", efekt:(2) },
{ idx:14, tresc:"Na przerwie podaczas grania w piłkę upadasz i łamiesz sobie rękę.</br>Cofasz się o 1 pole.", efekt:(-1) },
{ idx:15, tresc:"Na lekcji postanawiasz zrobić coś głupiego ale nauczyciel docenia twoje poczucie humoru.</br>Idziesz do przodu o 1 pole.", efekt:(1) },
{ idx:16, tresc:"Postanawisz zagrać z nauczycielem w papier, kamień, nożyce o ocenę. Wygrywasz i dostajesz 4.</br>Idziesz do przodu o 2 pola.", efekt:(2) },
{ idx:17, tresc:"Postanawisz zagrać z nauczycielem w papier, kamień, nożyce o ocenę. Przegrywasz i dostajesz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:18, tresc:"Postanawisz zagrać z nauczycielem w papier, kamień, nożyce o ocenę. Nayczeciel jest oburzony tym pomysłem. Dostajesz uwagę.</br>Cofasz się o 2 pola.", efekt:(-2) },
{ idx:19, tresc:"Poślizgnołeś/aś się na boisku od koszykówki ale nic ci nie jest.</br>Nic się nie dzieje.", efekt:(0) },
{ idx:20, tresc:"Dostajesz pochwałę za 100% frekwencję za miesiąc.</br>Idziesz do przodu o 2 pola.", efekt:(2) },
{ idx:21, tresc:"Dostajesz pochwałę za 100% frekwencję za półrocze.</br>Idziesz do przodu o 3 pola.", efekt:(3) },
{ idx:22, tresc:"Dostajesz pochwałę za 100% frekwencję za cały rok.</br>Idziesz do przodu o 4 pola.", efekt:(4) },
{ idx:23, tresc:"Nie udało ci się zaliczyć półrocza.</br>Cofasz się o 10 pól.", efekt:(-10) },
{ idx:24, tresc:"Nauczyciel przyłapał cię na używaniu telefonu. Na szczęście kazał ci tylko go schować.</br>Nic się nie dzieje.", efekt:(0) },
{ idx:25, tresc:"Nauczyciel przyłapał cię na używaniu telefonu. Niestety nie był łaskawy i dotajesz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:26, tresc:"Nauczyciel przyłapał cię na używaniu telefonu. Spytał się co tam na nim masz za ty postanowiłeś podzielić się tą informacją co rozbawiło nauczyciela.</br>Idziesz o 1 pole do przodu.", efekt:(1) },
{ idx:27, tresc:"Zasneło ci się na lekcji. Nauczyciel postanowił dać ci uwagę.</br>Cofasz się o 2 pola.", efekt:(-2) },
{ idx:28, tresc:"Zasneło ci się na leckji. Nauczyciel postanowił cię obudzić, po czym kontynuje lekcję.</br>Idziesz o 1 pole do przodu.", efekt:(1) },
{ idx:29, tresc:"Zasneło ci się na lekcji. Nauczyciel postanowił nic z tym nie robić i dalej prowadził lekcję.</br>Nic się nie dzieje.", efekt:(0) },
{ idx:30, tresc:"Podczas lekcji nagle słyszycie dźwięk próbnego alarmu i się ewakujecie.</br>Idziesz do przodu o 1 pole.", efekt:(1) },
{ idx:31, tresc:"Podczas lekcji w pracowni komputerowej grając w grę przegrywasz i uderzasz w stół niszcząc klawiaturę.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:32, tresc:"Na okienku postanawiacie wyjść sobie na jedzonko, niestety nauczyciel was widzi przez okno i po powrocie dostajecie uwagi.</br>Cofasz się o 2 pola.", efekt:(-2) },
{ idx:33, tresc:"Nauczyciel przyłapuje cię na ściąganiu na sprawdzianie. Dostajesz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
{ idx:34, tresc:"Nauczyciel ma dzisiaj urodziny. Wysyłacie delegację która ma za zadanie załatwić wolną lekcję. Udaje wam się.</br>Idziesz 1 pole do przodu.", efekt:(1) },
{ idx:35, tresc:"Podaczas lekcji w pracowni komputerowej ciekawi cię nazwa pliku, więc postanawiasz go otworzyć. Okazuje się być szkodliwym oprogramowaniem a komputer staje.</br>Cofasz się o 2 pola.", efekt:(-2) },
{ idx:36, tresc:"Podczas lekcji razem z nauczycielem szukacie błędu na tablicy. Znajdujesz go pierwszy/sza i dostajesz +.</br>Idziesz do przodu o 1 pole.", efekt:(1) },
{ idx:37, tresc:"Postanawiacie puścić muzykę na przerwie jednak klasa obok ma sprawdzian a nauczyciel nie wydaje się być zadowolony waszym pomysłem. Dostajecie uwagi.</br>Cofasz się o 2 pola.", efekt:(-2) },
{ idx:38, tresc:"Gdy używasz telefonu na lekcji nauczyciel nagle pyta się ciebie. Znasz odpowiedź i nie zgarniasz 1.</br>Stoisz w tym samym miejscu.", efekt:(0) },
{ idx:39, tresc:"Gdy używasz telefonu na lekcji nauczyciel nagle pyta się ciebie. Nie znasz odpowiedzi i zgarniasz 1.</br>Cofasz się o 3 pola.", efekt:(-3) },
];
